rules = [
  // ExplicitResultTypes (Disable for now since version dependent)
  DisableSyntax
  LeakingImplicitClassVal
  NoAutoTupling
  NoValInForComprehension
  ProcedureSyntax
  OrganizeImports
  RemoveUnused
]

DisableSyntax {
  noFinalize = true
  noImplicitConversion = true
  noImplicitObject = true
  noSemicolons = true
  noTabs = true
  noValPatterns = true
  noXml = true
}

ExplicitResultTypes {
  fatalWarnings = true
  skipSimpleDefinitions = false
}

OrganizeImports {
  groups = ["re:javax?\\.", "scala.", "com.exasol.", "*"]
  groupExplicitlyImportedImplicitsSeparately = true
}

RemoveUnused {
  // handled by OrganizeImports
  imports = false
}
