package com.exasol.common

object CommonConstants {
  val CONNECTION_NAME: String = "CONNECTION_NAME"
  val CONNECTION_PROPERTY_SEPARATOR: String = "CONNECTION_SEPARATOR"
  val DEFAULT_CONNECTION_PROPERTY_SEPARATOR_VALUE: String = ";"
  val CONNECTION_KEYVALUE_ASSIGNMENT: String = "CONNECTION_KEYVALUE_ASSIGNMENT"
  val CONNECTION_KEYVALUE_ASSIGNMENT_VALUE: String = "="
}
