name: CI Build Scala Linter
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scala-linter:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
      - name: Run scalafix linting
        run: |
          mvn --batch-mode clean compile test scalafix:scalafix \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false
