name: Release Droid - Prepare Original Checksum

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Scala version ${{ matrix.scala-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { scala-version: 'scala2.12' }
          - { scala-version: 'scala2.13' }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Run tests and build with Maven for ${{ matrix.scala-version }}
        run: |
          mvn --batch-mode clean verify --file pom.xml \
              -P${{ matrix.scala-version }}
      - name: Prepare checksum
        run: find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v3
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum
