name: Release Droid - Print Quick Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { scala-version: 'scala2.12', pk-skip: true }
          - { scala-version: 'scala2.13', pk-skip: false }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven skipping tests for ${{ matrix.scala-version }}
        run: |
          mvn --batch-mode clean verify \
              -P${{ matrix.scala-version }} \
              -DskipTests \
              -Dproject-keeper.skip=${{ matrix.pk-skip }}
      - name: Print checksum
        run: echo 'checksum_start==';find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + | xargs;echo '==checksum_end'

