name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Assets upload URL'
        required: true

jobs:
  build:
    name: Build for Scala version ${{ matrix.scala-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { scala-version: 'scala2.12', project-keeper-skip: true }
          - { scala-version: 'scala2.13', project-keeper-skip: false }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven skipping tests for ${{ matrix.scala-version }}
        run: |
          mvn --batch-mode clean verify \
              -P${{ matrix.scala-version }} \
              -DskipTests \
              -Dproject-keeper.skip=${{ matrix.project-keeper-skip }}
      - name: Generate sha256sum files
        run: find target -maxdepth 1 -name *.jar -exec bash -c 'sha256sum {} > {}.sha256' \;
      - name: Upload assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.jar
      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sha256
      - name: Upload error-code-report
        if: ${{ matrix.scala-version == 'scala2.13' }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json
