name: Release Droid - Print Quick Checksum

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Scala version ${{ matrix.scala-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { scala-version: 'scala2.12', project-keeper-skip: true }
          - { scala-version: 'scala2.13', project-keeper-skip: false }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven skipping tests for ${{ matrix.scala-version }}
        run: |
          mvn --batch-mode clean verify \
              -P${{ matrix.scala-version }} \
              -DskipTests \
              -Dproject-keeper.skip=${{ matrix.project-keeper-skip }}
      - name: Print checksum
        run: echo 'checksum_start==';find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + | xargs;echo '==checksum_end'
